image: alpine:latest

stages:
  - build_docker
  - deploy

variables:
  REPOSITORY_URL: 535114345906.dkr.ecr.ap-southeast-1.amazonaws.com/svara-company-web
  DOCKER_DRIVER: overlay2

services:
  - docker:18.06-dind

build_docker_image:
  stage: build_docker
  image: docker:stable
  script:
    - apk  add --no-cache curl jq python py-pip
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region ap-southeast-1)
    - docker build -t $REPOSITORY_URL:latest .
    - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:"${CI_BUILD_TAG}"
    - docker push $REPOSITORY_URL:"${CI_BUILD_TAG}"
    - docker push $REPOSITORY_URL:latest

deploy_production:
  stage: deploy
  only:
    - master
  when: manual
  script:
    - apk add --update openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh zamrud@180.250.18.114 -p 4322 'cd /home/aplikasi/cyclone/svara-company-web; git pull'
  environment:
    name: prod
    url: https://svara.id